[package]
name = "nero-wasm-host"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
semver = "1.0.27"
tokio = { workspace = true, features = ["fs"] }
wasm-metadata = "0.227.1"
wasmtime = { workspace = true }
